Repository mulesoft-catalyst/metrics-toolkit, pull requests merged in 2022-01, with the labels that each got.

#117 This is the new einstein feature
  .gitignore
  README.md
  README_sfdc.md
  pom.xml
  postman/postman_collection.json
  src/main/mule/aggregators/aggregator-platform-benefits-metrics.xml
  src/main/mule/aggregators/aggregator-sdlc-metrics.xml
  src/main/mule/api.xml
  src/main/mule/collectors/external/systems/collector-bitbucket.xml
  src/main/mule/collectors/external/systems/collector-confluence.xml
  src/main/mule/collectors/external/systems/collector-jenkins.xml
  src/main/mule/collectors/external/systems/collector-jira.xml
  src/main/mule/collectors/external/systems/collector-splunk.xml
  src/main/mule/loaders/loader-default.xml
  src/main/mule/loaders/loader-router.xml
  src/main/mule/loaders/loader-salesforce-analytics.xml
  src/main/mule/loaders/loader-splunk.xml
  src/main/mule/poller.xml
  src/main/mule/sources/external/systems/apis/api-call-bitbucket.xml
  src/main/mule/sources/external/systems/apis/api-call-confluence.xml
  src/main/mule/sources/external/systems/apis/api-call-jenkins.xml
  src/main/mule/sources/external/systems/apis/api-call-jira.xml
  src/main/mule/sources/external/systems/apis/api-call-splunk.xml
  src/main/resources/api/data-types/loaders/post-benefits-metrics.raml
  src/main/resources/dw/aggregation/build-sdlc-metrics-aggregation.dwl
  src/main/resources/dw/aggregation/build-sdlc-raw-data-response.dwl
  src/main/resources/dw/common/set-loader-details-from-props-var.dwl
  src/main/resources/dw/loader/loader-sfdc-build-benefits-structure.dwl
  src/main/resources/dw/loader/loader-sfdc-build-structure.dwl
  src/main/resources/properties/app-dev.yaml
  src/main/resources/properties/secure/app-dev.yaml
  src/main/resources/sfdc/blank_dataset.csv
  src/main/resources/sfdc/sfdc_platform_metrics.json
  src/main/resources/sfdc/sfdc_sdlc_metrics.json
  src/test/munit/unit-test-loader-platform-benefits-router.xml
  src/test/munit/unit-test-loader-platform-metrics-router.xml
  src/test/resources/dw/mock-loader-benefits-strategy-payload-sfdc.dwl
  src/test/resources/dw/mock-loader-strategy-payload-sfdc.dwl
Labels: invalid

#170 Introduce ability to ignore environments
  README.md
  src/main/mule/sources/anypoint/platform/apis/api-call-coreservices.xml
  src/main/resources/dw/anypoint/coreservices-filter-environments.dwl
  src/main/resources/properties/secure/app-dev.yaml
Labels: enhancement

#171 Changing year formatting from yyyy to uuuu to prevent parsing errors
  src/main/mule/sources/anypoint/platform/apis/api-call-mq.xml
  src/main/mule/sources/anypoint/platform/apis/api-call-osv2.xml
  src/main/resources/dw/aggregation/build-sdlc-metrics-aggregation.dwl
  src/main/resources/dw/loader/loader-sfdc-build-benefits-structure.dwl
  src/main/resources/dw/loader/loader-sfdc-build-structure.dwl
  src/main/resources/dw/loader/loader-tableau-write-operation-path.dwl
Labels: bug
